// Direct HLS (VOD) playback URLs for each session, resolved from Corrivium's
// public per-event config (https://site-assets.corrivium.live/cms/events/aws-summittlv26/<id>/prod/frontend.json).
// These manifests + segments are served with permissive CORS, so they can be
// played directly with hls.js instead of opening the original site.
export const VIDEO_SOURCES: Record<string, string> = {
  "tlv-key101": "https://aws-assets-cdg.stream.corrivium.live/aws-summittlv26/outputs/mediaconvert/27/hls/v1/index.m3u8",
  "tlv-dvt201": "https://aws-assets-cdg.stream.corrivium.live/aws-summittlv26/outputs/mediaconvert/61/hls/v1/index.m3u8",
  "tlv-dvt202": "https://aws-assets-cdg.stream.corrivium.live/aws-summittlv26/outputs/mediaconvert/50/hls/v1/index.m3u8",
  "tlv-dvt203": "https://aws-assets-cdg.stream.corrivium.live/aws-summittlv26/outputs/mediaconvert/48/hls/v1/index.m3u8",
  "tlv-dvt301": "https://aws-assets-cdg.stream.corrivium.live/aws-summittlv26/outputs/mediaconvert/52/hls/v1/index.m3u8",
  "tlv-aim201": "https://aws-assets-cdg.stream.corrivium.live/aws-summittlv26/outputs/mediaconvert/47/hls/v1/index.m3u8",
  "tlv-aim202": "https://aws-assets-cdg.stream.corrivium.live/aws-summittlv26/outputs/mediaconvert/49/hls/v1/index.m3u8",
  "tlv-aim301": "https://aws-assets-cdg.stream.corrivium.live/aws-summittlv26/outputs/mediaconvert/62/hls/v1/index.m3u8",
  "tlv-aim302": "https://aws-assets-cdg.stream.corrivium.live/aws-summittlv26/outputs/mediaconvert/53/hls/v1/index.m3u8",
  "tlv-svs301": "https://aws-assets-cdg.stream.corrivium.live/aws-summittlv26/outputs/mediaconvert/22/hls/v1/index.m3u8",
  "tlv-svs303": "https://aws-assets-cdg.stream.corrivium.live/aws-summittlv26/outputs/mediaconvert/36/hls/v1/index.m3u8",
  "tlv-svs304": "https://aws-assets-cdg.stream.corrivium.live/aws-summittlv26/outputs/mediaconvert/54/hls/v1/index.m3u8",
  "tlv-svs305": "https://aws-assets-cdg.stream.corrivium.live/aws-summittlv26/outputs/mediaconvert/65/hls/v1/index.m3u8",
  "tlv-svs306": "https://aws-assets-cdg.stream.corrivium.live/aws-summittlv26/outputs/mediaconvert/28/hls/v1/index.m3u8",
  "tlv-svs401": "https://aws-assets-cdg.stream.corrivium.live/aws-summittlv26/outputs/mediaconvert/42/hls/v1/index.m3u8",
  "tlv-ant201": "https://aws-assets-cdg.stream.corrivium.live/aws-summittlv26/outputs/mediaconvert/29/hls/v1/index.m3u8",
  "tlv-ant302": "https://aws-assets-cdg.stream.corrivium.live/aws-summittlv26/outputs/mediaconvert/24/hls/v1/index.m3u8",
  "tlv-ant303": "https://aws-assets-cdg.stream.corrivium.live/aws-summittlv26/outputs/mediaconvert/44/hls/v1/index.m3u8",
  "tlv-ant304": "https://aws-assets-cdg.stream.corrivium.live/aws-summittlv26/outputs/mediaconvert/69/hls/v2/index.m3u8",
  "tlv-ant305": "https://aws-assets-cdg.stream.corrivium.live/aws-summittlv26/outputs/mediaconvert/38/hls/v1/index.m3u8",
  "tlv-ant306": "https://aws-assets-cdg.stream.corrivium.live/aws-summittlv26/outputs/mediaconvert/64/hls/v1/index.m3u8",
  "tlv-dat202": "https://aws-assets-cdg.stream.corrivium.live/aws-summittlv26/outputs/mediaconvert/23/hls/v1/index.m3u8",
  "tlv-dat306": "https://aws-assets-cdg.stream.corrivium.live/aws-summittlv26/outputs/mediaconvert/39/hls/v1/index.m3u8",
  "tlv-dat307": "https://aws-assets-cdg.stream.corrivium.live/aws-summittlv26/outputs/mediaconvert/45/hls/v1/index.m3u8",
  "tlv-dat308": "https://aws-assets-cdg.stream.corrivium.live/aws-summittlv26/outputs/mediaconvert/58/hls/v1/index.m3u8",
  "tlv-dat309": "https://aws-assets-cdg.stream.corrivium.live/aws-summittlv26/outputs/mediaconvert/60/hls/v1/index.m3u8",
  "tlv-dat310": "https://aws-assets-cdg.stream.corrivium.live/aws-summittlv26/outputs/mediaconvert/30/hls/v1/index.m3u8",
  "tlv-arc301": "https://aws-assets-cdg.stream.corrivium.live/aws-summittlv26/outputs/mediaconvert/40/hls/v1/index.m3u8",
  "tlv-arc302": "https://aws-assets-cdg.stream.corrivium.live/aws-summittlv26/outputs/mediaconvert/66/hls/v1/index.m3u8",
  "tlv-arc303": "https://aws-assets-cdg.stream.corrivium.live/aws-summittlv26/outputs/mediaconvert/46/hls/v1/index.m3u8",
  "tlv-arc304": "https://aws-assets-cdg.stream.corrivium.live/aws-summittlv26/outputs/mediaconvert/32/hls/v1/index.m3u8",
  "tlv-arc305": "https://aws-assets-cdg.stream.corrivium.live/aws-summittlv26/outputs/mediaconvert/21/hls/v1/index.m3u8",
  "tlv-arc401": "https://aws-assets-cdg.stream.corrivium.live/aws-summittlv26/outputs/mediaconvert/57/hls/v1/index.m3u8",
  "tlv-sec301": "https://aws-assets-cdg.stream.corrivium.live/aws-summittlv26/outputs/mediaconvert/56/hls/v1/index.m3u8",
  "tlv-sec302": "https://aws-assets-cdg.stream.corrivium.live/aws-summittlv26/outputs/mediaconvert/31/hls/v1/index.m3u8",
  "tlv-sec303": "https://aws-assets-cdg.stream.corrivium.live/aws-summittlv26/outputs/mediaconvert/37/hls/v1/index.m3u8",
  "tlv-sec304": "https://aws-assets-cdg.stream.corrivium.live/aws-summittlv26/outputs/mediaconvert/63/hls/v1/index.m3u8",
  "tlv-sec305": "https://aws-assets-cdg.stream.corrivium.live/aws-summittlv26/outputs/sec305/hls/v1/index.m3u8",
  "tlv-dem301": "https://aws-assets-cdg.stream.corrivium.live/aws-summittlv26/outputs/mediaconvert/20/hls/v1/index.m3u8",
  "tlv-dem302": "https://aws-assets-cdg.stream.corrivium.live/aws-summittlv26/outputs/mediaconvert/67/hls/v1/index.m3u8",
  "tlv-dem303": "https://aws-assets-cdg.stream.corrivium.live/aws-summittlv26/outputs/mediaconvert/41/hls/v1/index.m3u8",
  "tlv-dem304": "https://aws-assets-cdg.stream.corrivium.live/aws-summittlv26/outputs/mediaconvert/34/hls/v1/index.m3u8",
  "tlv-dem305": "https://aws-assets-cdg.stream.corrivium.live/aws-summittlv26/outputs/mediaconvert/59/hls/v1/index.m3u8",
  "tlv-dem306": "https://aws-assets-cdg.stream.corrivium.live/aws-summittlv26/outputs/mediaconvert/68/hls/v1/index.m3u8",
  "tlv-dem307": "https://aws-assets-cdg.stream.corrivium.live/aws-summittlv26/outputs/mediaconvert/51/hls/v1/index.m3u8",
  "tlv-dem308": "https://aws-assets-cdg.stream.corrivium.live/aws-summittlv26/outputs/mediaconvert/43/hls/v1/index.m3u8",
  "tlv-dem309": "https://aws-assets-cdg.stream.corrivium.live/aws-summittlv26/outputs/mediaconvert/35/hls/v1/index.m3u8",
  "tlv-dem310": "https://aws-assets-cdg.stream.corrivium.live/aws-summittlv26/outputs/mediaconvert/33/hls/v1/index.m3u8",
};
